version: '3.4'

services:
  minio:
    image: docker.io/bitnami/minio:2022
    
  mongodb:
    image: mongo
  
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
      
  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2
    
  userdb:
    image: postgres
    
  dealdb:
    image: postgres
    
  addb:
    image: postgres
    
  user.api:
    image: ${DOCKER_REGISTRY-}userapi
    build:
      context: .
      dockerfile: Services/User.Service/User.Api/Dockerfile
  
  deal.api:
    image: ${DOCKER_REGISTRY-}dealapi
    build:
      context: .
      dockerfile: Services/Deal.Service/Deal.Api/Dockerfile
      
  ad.api:
    image: ${DOCKER_REGISTRY-}adapi
    build:
      context: .
      dockerfile: Services/Ad.Service/Ad.Api/Dockerfile
      
  chat.api:
    image: ${DOCKER_REGISTRY-}chatapi
    build:
      context: .
      dockerfile: Services/Chat.Service/Chat.Api/Dockerfile
      
  bff.api:
    image: ${DOCKER_REGISTRY-}bffapi
    build:
      context: .
      dockerfile: Api.Gateway/Bff.Api/Dockerfile

networks:
  elastic:
    driver: bridge
    
volumes:
  postgres_data:
  mongo_data:
  minio_data:
  elasticsearch-data:
  rabbitmq: